spring:
  application:
    name: CrowdfundingPlatform

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  stripe:
    secret-key: ${SK_TEST}
    publishable-key: ${PK_TEST}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

server:
    port: ${SERVER_PORT:8443}
    ssl:
      enabled: ${SSL_ENABLED:true}
      key-store: ${SSL_KEY_STORE:ssl/crowdfunding-platform.jks}
      key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
      key-password: ${SSL_KEY_PASSWORD:${SSL_KEY_STORE_PASSWORD:changeit}}
      key-store-type: ${SSL_KEY_STORE_TYPE:JKS}
      key-alias: ${SSL_KEY_ALIAS:crowdfunding-platform}