spring:
  application:
    name: CrowdfundingPlatform

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  stripe:
    secret-key: ${SK_TEST}
    publishable-key: ${PK_TEST}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  server:
    port: 8080