spring:
  application:
    name: CrowdfundingPlatform

  datasource:
    url: JDBC:postgresql://localhost:5432/crowdfunding_db
    username: postgres
    password: "2012"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  stripe:
    secret-key: ${SK_TEST}
    publishable-key: ${PK_TEST}